##Making the dataset

In [10]:
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv('dataset.csv')

In [5]:
df=pd.DataFrame(dataset)

In [6]:
df.head()

temperature  humidity  vibrations  speed temperature_status  \
0        35.33     63.21        1.02  59.01             MEDIUM   
1        28.82     68.18        1.59  88.59             NORMAL   
2        25.76     69.06        0.94  13.40             NORMAL   
3        24.53     74.19        1.64  32.83             NORMAL   
4        35.45     66.37        1.24   5.95             MEDIUM   

  humidity_status vibrations_status speed_status  
0          NORMAL            NORMAL          LOW  
1             LOW              HIGH         HIGH  
2             LOW            NORMAL       NORMAL  
3            HIGH              HIGH       NORMAL  
4          NORMAL               LOW       NORMAL

In [9]:
df['Issue']=" "

In [14]:
n=len(df. index)

In [15]:
print(n)

5000


In [17]:

for i in range(n):
  if (df['temperature_status'][i]=="NORMAL" and df['humidity_status'][i]=="NORMAL" and df['vibrations_status'][i]=="NORMAL" and df['speed_status'][i]=="NORMAL" ):
    df['Issue']="NO"

  elif (df['temperature_status'][i]=="MEDIUM" and df['humidity_status'][i]=="MEDIUM" and df['vibrations_status'][i]=="MEDIUM" and df['speed_status'][i]=="MEDIUM" ):
    df['Issue']="NO"

  else:
    df['Issue']="YES"


In [18]:
df.head()

temperature  humidity  vibrations  speed temperature_status  \
0        35.33     63.21        1.02  59.01             MEDIUM   
1        28.82     68.18        1.59  88.59             NORMAL   
2        25.76     69.06        0.94  13.40             NORMAL   
3        24.53     74.19        1.64  32.83             NORMAL   
4        35.45     66.37        1.24   5.95             MEDIUM   

  humidity_status vibrations_status speed_status Issue  
0          NORMAL            NORMAL          LOW   YES  
1             LOW              HIGH         HIGH   YES  
2             LOW            NORMAL       NORMAL   YES  
3            HIGH              HIGH       NORMAL   YES  
4          NORMAL               LOW       NORMAL   YES

In [32]:
df['is_Issue'] = (df.Issue == "YES").astype(int)

In [34]:
df['is_Issue'].value_counts()

1    5000
Name: is_Issue, dtype: int64

In [42]:
df = df.drop('is_Issue', axis=1)

In [44]:
df.to_csv('DATASET.csv', index=False)

##**Starting**


In [37]:
import tensorflow as tf

In [74]:
dataset = pd.read_csv('DATASET.csv')


In [75]:
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
dataset['Issue']= label_encoder.fit_transform(df['Issue'])

In [76]:
X = dataset.iloc[:, :4].values
y = dataset.iloc[:, -1].values

In [77]:
print(X)

[[35.33 63.21  1.02 59.01]
 [28.82 68.18  1.59 88.59]
 [25.76 69.06  0.94 13.4 ]
 ...
 [38.82 74.47  1.35 89.87]
 [37.79 64.2   1.19 44.12]
 [35.58 66.29  1.07  8.16]]


In [78]:
print(y)

[0 0 0 ... 0 0 0]


In [79]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

##Building model

In [80]:
ann = tf.keras.models.Sequential()

In [81]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))


Compiling

In [82]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [84]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
125/125 [==============================] - 0s 2ms/step - loss: 4.5300e-11 - accuracy: 1.0000
Epoch 2/100
125/125 [==============================] - 0s 2ms/step - loss: 4.1417e-11 - accuracy: 1.0000
Epoch 3/100
125/125 [==============================] - 0s 2ms/step - loss: 3.7992e-11 - accuracy: 1.0000
Epoch 4/100
125/125 [==============================] - 0s 2ms/step - loss: 3.4965e-11 - accuracy: 1.0000
Epoch 5/100
125/125 [==============================] - 0s 2ms/step - loss: 3.2263e-11 - accuracy: 1.0000
Epoch 6/100
125/125 [==============================] - 0s 2ms/step - loss: 2.9846e-11 - accuracy: 1.0000
Epoch 7/100
125/125 [==============================] - 0s 2ms/step - loss: 2.7659e-11 - accuracy: 1.0000
Epoch 8/100
125/125 [==============================] - 0s 2ms/step - loss: 2.5698e-11 - accuracy: 1.0000
Epoch 9/100
125/125 [==============================] - 0s 2ms/step - loss: 2.3924e-11 - accuracy: 1.0000
Epoch 10/100
125/125 [==============================] -

In [93]:
ann.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 6)                 30        
                                                                 
 dense_7 (Dense)             (None, 6)                 42        
                                                                 
 dense_8 (Dense)             (None, 1)                 7         
                                                                 
Total params: 79
Trainable params: 79
Non-trainable params: 0
_________________________________________________________________


In [94]:
y_pred=ann.predict(X_train).astype('int32')

125/125 [==============================] - 0s 3ms/step


In [102]:
test_loss, test_accuracy = ann.evaluate(X_test, y_test, verbose=0)
print('Test accuracy:', test_accuracy)

Test accuracy: 1.0


In [105]:
import pickle
# open a file, where you ant to store the data
file = open('Tarp ann.pkl', 'wb')

# dump information to that file
pickle.dump(ann, file)

Keras weights file (<HDF5 file "variables.h5" (mode r+)>) saving:
...layers
......dense
.........vars
............0
............1
......dense_1
.........vars
............0
............1
......dense_2
.........vars
............0
............1
...metrics
......mean
.........vars
............0
............1
......mean_metric_wrapper
.........vars
............0
............1
...optimizer
......vars
.........0
.........1
.........10
.........11
.........12
.........2
.........3
.........4
.........5
.........6
.........7
.........8
.........9
...vars
Keras model archive saving:
File Name                                             Modified             Size
metadata.json                                  2023-03-28 06:22:34           64
config.json                                    2023-03-28 06:22:34         1793
variables.h5                                   2023-03-28 06:22:34        25088
